const AWS_BUCKET_NAME = "yatin-files";
const AWS_BUCKET_REGION = "us-east-2";
const AWS_ARN = "arn:aws:s3:::yatin-files";
const AWS_ACCESS_KEY = "AKIA6OOYMDALVH6KMUG2";
const AWS_SECRET_KEY = "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";

/**
 * Firebase Config
 */
const FIREBASE_BUCKET_URL = "gs://yatinapp-a7d15.appspot.com";
const FIREBASE_API_KEY = "AIzaSyDyYuT4ewulSwJzrU_fBj-YPDJwMNH0S8g";
const FIREBASE_AUTH_DOMAIN = "yatinapp-a7d15.firebaseapp.com";
const FIREBASE_PROJECTID = "yatinapp-a7d15";
const FIREBASE_STORAGE_BUCKET = "yatinapp-a7d15.appspot.com";
const FIREBASE_MESSAGING_SENDER_ID = "361193968344";
const FIREBASE_APP_ID = "1:361193968344:web:e1651b815e448e7a2fbdad";
const FIREBASE_MEASUREMENT_ID = "G-NCVB54WJBG";


module.exports = {
    AWS_BUCKET_NAME,
    AWS_BUCKET_REGION,
    AWS_ARN,
    AWS_ACCESS_KEY,
    AWS_SECRET_KEY,
    //FIREBASE - CONSTANTS
    FIREBASE_BUCKET_URL,
    FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECTID,
    FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID
}